sudo: required

services:
  - docker

script:
  - echo 'CI work is nothing. This Travis CI project run for Docker image build jobs.'

deploy:
  provider: script
  script: bash build_image.sh
  on:
    branch: master

branches:
  only:
    - master
